name: CoolApkFollow

on:
  push:
    paths:
      - 'coolapkfollow.py'
      - '.github/workflows/coolapkfollow.yml'
  schedule:
    - cron: 30 10 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Set proxy
        uses: w311ang/setproxy@main
        with:
          config: ${{ secrets.ss_config }}
          password: ${{ secrets.frp_auth }}
          redirect: ${{ secrets.frp_redirect }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ./coolapkfollow.json
          key: ${{ github.workflow }}-${{ github.run_id }}
          restore-keys: |
            ${{ github.workflow }}-
      - name: Run
        env:
          on: ${{ github.event_name }}
          jmail: ${{ secrets.jmail_password }}
          token: ${{ secrets.coolapkfollow_token }}
          followuser: ${{ secrets.coolapkfollow_followuser }}
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 5
          command: |
            proxychains python -u coolapkfollow.py
          on_retry_command: sudo systemctl restart shadowsocks-libev-local@client; sleep 5s
      - uses: gautamkrishnar/keepalive-workflow@master
