name: ISL_Check

on:
  push:
    paths-ignore:
      - 'README.md'
  schedule:
    - cron: 0 * * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Setup pytools
        run: |
          curl -O https://raw.githubusercontent.com/w311ang/pytools/main/pytools.py
          curl -O https://raw.githubusercontent.com/w311ang/pytools/main/aes.py
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ./hkisl.txt
          key: hkisl-${{ github.run_id }}
          restore-keys: |
            hkisl-
      - name: Run
        env:
          jmail: ${{ secrets.jmail_password }}
        run: |
          python -u hkisl.py
