# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: signin

on:
  push:
    branches: [ main ]
    paths:
      - 'xc_signin.py'
      - 'zhuan.py'
      - 'sjly.py'
  watch:
    types: started
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    environment: Production

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: xcysc
      env:
        username: ${{ secrets.xc_username }}
        password: ${{ secrets.xc_password }}
      run: |
        python xc_signin.py
    - name: sjly
      env:
        id: ${{ secrets.sjly_id }}
      run: |
        python sjly.py
    - name: zhuan
      env:
        ppu: ${{ secrets.zhuan_ppu }}
      run: |
        python zhuan.py
