# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: signin

on:
  push:
    branches: [ main ]
    paths:
      - 'xc_signin.py'
      - 'zhuan.py'
      - 'sjly.py'
#  watch:
#    types: started
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    #if: github.event.repository.owner.id == github.event.sender.id
    environment: Production

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Set proxy
      uses: w311ang/setproxy@main
      with:
        config: ${{ secrets.ss_config }}
    - name: Setup pytools
      run: |
        curl -O https://raw.githubusercontent.com/w311ang/pytools/main/pytools.py
        curl -O https://raw.githubusercontent.com/w311ang/pytools/main/aes.py
    - name: xcysc
      if: always()
      env:
        username: ${{ secrets.xc_username }}
        password: ${{ secrets.xc_password }}
      run: |
        proxychains python -u xc_signin.py
    - name: sjly
      if: always()
      env:
        id: ${{ secrets.sjly_id }}
      run: |
        proxychains python -u sjly.py
    - name: zhuan
      if: always()
      env:
        cookie: ${{ secrets.zhuan_cookie }}
      run: |
        proxychains python -u zhuan.py
    - name: Run
      env:
        jmail: ${{ secrets.jmail_password }}
      run: |
        python -u hkisl.py
