name: WX Reward

on:
  push:
    paths:
      - 'wx/reward.py'
      - '.github/workflows/wx.yml'
  schedule:
    - cron: 0,30 * * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Set proxy
        uses: w311ang/setproxy@main
        with:
          config: ${{ secrets.ss_config }}
      - name: Cache wx
        uses: actions/cache@v2
        with:
          path: wx/itchat.pkl
          key: wx-${{ github.run_id }}
          restore-keys: |
            wx-
      - name: Run
        run: |
          cd wx
          proxychains python -u reward.py
